"""
PDF generation service for Purchase Orders.
Extracted from main.py — raw PDF stream builder using no external libraries.
"""
from typing import List


def _pdf_escape(text: str) -> str:
    return text.replace("\\", "\\\\").replace("(", "\\(").replace(")", "\\)")


def _pdf_text(commands: List[str], x: float, y: float, text: str, size: int = 12, bold: bool = False):
    font_name = "F2" if bold else "F1"
    commands.append(
        f"BT /{font_name} {size} Tf 1 0 0 1 {x:.2f} {y:.2f} Tm ({_pdf_escape(text)}) Tj ET"
    )


def _wrap_pdf_text(text: str, width: int = 72) -> List[str]:
    words = text.split()
    if not words:
        return [""]
    lines = []
    current = words[0]
    for word in words[1:]:
        candidate = f"{current} {word}"
        if len(candidate) <= width:
            current = candidate
        else:
            lines.append(current)
            current = word
    lines.append(current)
    return lines


def build_purchase_order_pdf(document: dict) -> bytes:
    """Generate a PDF from a PO document dict. Returns raw PDF bytes."""
    commands: List[str] = []
    commands.append("0.09 0.29 0.78 rg 40 720 532 48 re f")
    commands.append("1 1 1 rg")
    _pdf_text(commands, 56, 750, document["companyName"], size=19, bold=True)
    _pdf_text(commands, 56, 732, "Purchase Order", size=11, bold=False)
    commands.append("0 g")

    _pdf_text(commands, 420, 750, document["poNumber"], size=15, bold=True)
    _pdf_text(commands, 420, 734, f"Issue Date: {document['issueDate'][:10]}", size=10)
    if document.get("deliveryDate"):
        _pdf_text(commands, 420, 720, f"Delivery: {document['deliveryDate'][:10]}", size=10)

    _pdf_text(commands, 40, 690, "Supplier", size=11, bold=True)
    _pdf_text(commands, 320, 690, "Bill To", size=11, bold=True)
    commands.append("0.85 G 40 682 m 572 682 l S")

    supplier_lines = [document["supplierName"], document.get("supplierAddress") or "", document.get("supplierEmail") or ""]
    bill_lines = [document["billToCompany"], document["billToAddress"], document["companyAddress"]]

    y_supplier = 664
    for line in supplier_lines:
        if line:
            _pdf_text(commands, 40, y_supplier, line, size=10, bold=(y_supplier == 664))
            y_supplier -= 16

    y_bill = 664
    for line in bill_lines:
        if line:
            _pdf_text(commands, 320, y_bill, line, size=10, bold=(y_bill == 664))
            y_bill -= 16

    commands.append("0.95 g 40 576 532 24 re f")
    commands.append("0 g")
    _pdf_text(commands, 52, 584, "Description", size=10, bold=True)
    _pdf_text(commands, 275, 584, "Qty", size=10, bold=True)
    _pdf_text(commands, 355, 584, "Rate", size=10, bold=True)
    _pdf_text(commands, 455, 584, "Amount", size=10, bold=True)

    y_row = 556
    for item in document["items"][:6]:
        _pdf_text(commands, 52, y_row, f"{item['description']} ({item.get('sku', 'N/A')})", size=10)
        _pdf_text(commands, 280, y_row, str(item["quantity"]), size=10)
        _pdf_text(commands, 355, y_row, f"${item['rate']:.2f}", size=10)
        _pdf_text(commands, 455, y_row, f"${item['amount']:.2f}", size=10)
        commands.append(f"0.88 G 40 {y_row - 8:.2f} m 572 {y_row - 8:.2f} l S")
        y_row -= 24

    totals_top = max(y_row - 18, 420)
    _pdf_text(commands, 360, totals_top, "Subtotal", size=10, bold=True)
    _pdf_text(commands, 455, totals_top, f"${document['subtotal']:.2f}", size=10)
    _pdf_text(commands, 360, totals_top - 20, f"Tax ({document['taxRate']:.0f}%)", size=10, bold=True)
    _pdf_text(commands, 455, totals_top - 20, f"${document['tax']:.2f}", size=10)
    commands.append("0.09 0.29 0.78 rg 350 368 190 30 re f")
    commands.append("1 1 1 rg")
    _pdf_text(commands, 364, 378, "Total", size=11, bold=True)
    _pdf_text(commands, 455, 378, f"${document['total']:.2f}", size=11, bold=True)
    commands.append("0 g")

    _pdf_text(commands, 40, 334, "Notes", size=11, bold=True)
    commands.append("0.90 G 40 326 m 572 326 l S")
    note_y = 306
    for line in _wrap_pdf_text(document.get("notes") or "", width=82)[:4]:
        _pdf_text(commands, 40, note_y, line, size=10)
        note_y -= 15

    _pdf_text(commands, 40, 104, "Generated by ChainMind Procurement Intelligence", size=9)

    stream = "\n".join(commands).encode("latin-1", "replace")
    objects = [
        b"<< /Type /Catalog /Pages 2 0 R >>",
        b"<< /Type /Pages /Kids [3 0 R] /Count 1 >>",
        b"<< /Type /Page /Parent 2 0 R /MediaBox [0 0 612 792] /Resources << /Font << /F1 4 0 R /F2 5 0 R >> >> /Contents 6 0 R >>",
        b"<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>",
        b"<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica-Bold >>",
        b"<< /Length " + str(len(stream)).encode("latin-1") + b" >>\nstream\n" + stream + b"\nendstream",
    ]

    pdf = bytearray(b"%PDF-1.4\n%\xe2\xe3\xcf\xd3\n")
    offsets = [0]
    for index, obj in enumerate(objects, start=1):
        offsets.append(len(pdf))
        pdf.extend(f"{index} 0 obj\n".encode("latin-1"))
        pdf.extend(obj)
        pdf.extend(b"\nendobj\n")

    xref_start = len(pdf)
    pdf.extend(f"xref\n0 {len(objects) + 1}\n".encode("latin-1"))
    pdf.extend(b"0000000000 65535 f \n")
    for offset in offsets[1:]:
        pdf.extend(f"{offset:010d} 00000 n \n".encode("latin-1"))
    pdf.extend(
        (f"trailer\n<< /Size {len(objects) + 1} /Root 1 0 R >>\nstartxref\n{xref_start}\n%%EOF").encode("latin-1")
    )
    return bytes(pdf)
