/**
 * explainableInsights.ts
 *
 * AI Explainable Insights Layer for Demand Forecasting.
 *
 * Collects raw internal signals (model, festivals, weather, trend) from:
 *   - SmartForecastOutput  (forecastEngine.ts)
 *   - generateInsights()   (externalIntelligence.ts)
 *
 * Sends them to Groq API -> returns polished, human-readable explanation strings.
 * Falls back to cleaned internal strings if Groq is unavailable.
 *
 * IMPORTANT: Does NOT modify forecast logic. Read-only consumer of signals.
 *
 * Usage:
 *   import { buildExplainableInsights } from "./explainableInsights";
 *
 *   const explanations = await buildExplainableInsights({
 *     smartOutput,          // from generateSmartForecast()
 *     externalInsights,     // from generateInsights()
 *     groqApiKey,           // process.env.GROQ_API_KEY or user-supplied
 *     productName,
 *     category,
 *   });
 *   // store explanations in state, surface in UI later
 */

// ---------------------------------------------------------------------------
// SECTION 1: TYPES
// ---------------------------------------------------------------------------

/** Mirrors SmartForecastOutput from forecastEngine.ts - no circular import needed */
export interface ForecastSignals {
  summary: {
    forecastTotal: number;
    avgDailyDemand: number;
    trend: "increasing" | "decreasing" | "stable";
    demandType: "Smooth" | "Erratic" | "Intermittent" | "Seasonal" | "New";
    confidence: "High" | "Medium" | "Low";
  };
  model: {
    name: string;
    reason: string;
  };
  meta: {
    appliedFestivalDays: number;
    dataPointsUsed: number;
  };
  /** Festival names that appeared in the forecast window (deduplicated) */
  festivalNames?: string[];
}

export interface ExplainableInsightsInput {
  /** SmartForecastOutput.summary + .model + .meta + optional festival names */
  forecastSignals: ForecastSignals;
  /** String array returned by generateInsights() from externalIntelligence.ts */
  externalInsights: string[];
  /** Your Groq API key - pass from env or config */
  groqApiKey: string;
  /** Product display name (e.g. "Umbrella Pro Max") */
  productName: string;
  /** Product category string (e.g. "Fashion") */
  category: string;
}

export interface ExplainableInsightResult {
  /** Final insights to store in state and show in UI */
  insights: string[];
  /** Whether Groq was used or fallback fired */
  source: "groq" | "fallback";
  /** ISO timestamp of generation */
  generatedAt: string;
}

// ---------------------------------------------------------------------------
// SECTION 2: CONSTANTS
// ---------------------------------------------------------------------------

const GROQ_API_URL = "https://api.groq.com/openai/v1/chat/completions";
const GROQ_MODEL = "llama3-8b-8192";
const GROQ_MAX_TOKENS = 512;
const GROQ_TIMEOUT_MS = 8000;

// ---------------------------------------------------------------------------
// SECTION 3: SIGNAL ASSEMBLER
// Converts typed signals into a compact, structured text block for the prompt.
// ---------------------------------------------------------------------------

const assembleSignalBlock = (
  input: ExplainableInsightsInput,
): string => {
  const { forecastSignals, externalInsights, productName, category } = input;
  const { summary, model, meta, festivalNames } = forecastSignals;

  const lines: string[] = [
    `Product: ${productName || "Unknown"}`,
    `Category: ${category || "Unknown"}`,
    `Forecast Model Used: ${model.name} - ${model.reason}`,
    `Demand Type: ${summary.demandType}`,
    `Trend Direction: ${summary.trend}`,
    `Confidence Level: ${summary.confidence}`,
    `Total Forecast Value: ${summary.forecastTotal.toLocaleString()}`,
    `Average Daily Demand: ${summary.avgDailyDemand.toLocaleString()}`,
    `Data Points Used: ${meta.dataPointsUsed}`,
    `Festival-Affected Forecast Days: ${meta.appliedFestivalDays}`,
  ];

  if (festivalNames && festivalNames.length > 0) {
    lines.push(`Festivals in Window: ${festivalNames.slice(0, 5).join(", ")}`);
  } else {
    lines.push("Festivals in Window: None detected");
  }

  if (externalInsights.length > 0) {
    lines.push("External Intelligence Signals:");
    externalInsights.forEach((signal) => lines.push(`  - ${signal}`));
  }

  return lines.join("\n");
};

// ---------------------------------------------------------------------------
// SECTION 4: PROMPT BUILDER
// ---------------------------------------------------------------------------

const buildGroqPrompt = (signalBlock: string): string => `
You are an AI forecasting assistant inside a supply chain intelligence platform.

Below are internal signals generated by the demand forecasting engine for a product.
Your job is to convert these raw signals into 4-6 clear, professional, human-readable 
insight sentences that a business analyst or supply chain manager would find useful.

Rules:
- Do NOT invent numbers or facts not present in the signals.
- Do NOT mention technical model names like "LLM" or "neural network".
- Sound confident but not overpromising.
- Each sentence should be on its own line.
- Start each sentence with a relevant emoji (📊 📈 🌦️ 🎉 ⚠️ 🔍 📦).
- Keep each sentence under 25 words.
- Do NOT use bullet points, numbering, or markdown.

Internal Signals:
${signalBlock}

Generate the insights now:
`.trim();

// ---------------------------------------------------------------------------
// SECTION 5: GROQ API CALL
// ---------------------------------------------------------------------------

const callGroqAPI = async (
  prompt: string,
  apiKey: string,
): Promise<string[] | null> => {
  const controller = new AbortController();
  const timeout = setTimeout(() => controller.abort(), GROQ_TIMEOUT_MS);

  try {
    const response = await fetch(GROQ_API_URL, {
      method: "POST",
      signal: controller.signal,
      headers: {
        "Content-Type": "application/json",
        Authorization: `Bearer ${apiKey}`,
      },
      body: JSON.stringify({
        model: GROQ_MODEL,
        max_tokens: GROQ_MAX_TOKENS,
        temperature: 0.4,
        messages: [
          {
            role: "system",
            content:
              "You are a concise, professional demand forecasting analyst. Always respond with plain sentences only - no lists, no markdown, no headers.",
          },
          {
            role: "user",
            content: prompt,
          },
        ],
      }),
    });

    clearTimeout(timeout);

    if (!response.ok) {
      return null;
    }

    const data = await response.json();
    const rawText: string =
      data?.choices?.[0]?.message?.content ?? "";

    if (!rawText.trim()) {
      return null;
    }

    const lines = rawText
      .split(/\n+/)
      .map((line: string) => line.trim())
      .filter((line: string) => line.length > 8);

    return lines.length > 0 ? lines : null;
  } catch {
    clearTimeout(timeout);
    return null;
  }
};

// ---------------------------------------------------------------------------
// SECTION 6: FALLBACK BUILDER
// ---------------------------------------------------------------------------

const buildFallbackInsights = (
  input: ExplainableInsightsInput,
): string[] => {
  const { forecastSignals, externalInsights, productName } = input;
  const { summary, model, meta, festivalNames } = forecastSignals;

  const insights: string[] = [];

  insights.push(
    `📊 Forecast generated using ${model.name} - ${model.reason.toLowerCase()}.`,
  );

  const demandDescriptions: Record<string, string> = {
    Smooth: "demand is stable and consistent, supporting reliable planning.",
    Erratic: "demand shows high variability - widen safety stock buffers.",
    Intermittent: "demand is irregular with frequent low-activity periods.",
    Seasonal: "a repeating seasonal pattern has been detected in this product.",
    New: "limited history available - forecast is based on recent observations.",
  };
  const demandDesc = demandDescriptions[summary.demandType] ?? "demand pattern has been analyzed.";
  insights.push(`🔍 For ${productName || "this product"}, ${demandDesc}`);

  if (summary.trend === "increasing") {
    insights.push("📈 Demand trend is increasing - consider raising procurement volumes.");
  } else if (summary.trend === "decreasing") {
    insights.push("📉 Demand trend is declining - review stock levels to avoid overstock.");
  } else {
    insights.push("📊 Demand trend is stable - baseline planning assumptions hold.");
  }

  if (summary.confidence === "High") {
    insights.push("✅ Forecast confidence is high - signals are consistent and data quality is strong.");
  } else if (summary.confidence === "Medium") {
    insights.push("⚠️ Forecast confidence is moderate - minor variability detected in signals.");
  } else {
    insights.push("⚠️ Forecast confidence is low - use wider buffers and review data coverage.");
  }

  if (meta.appliedFestivalDays > 0) {
    const festList =
      festivalNames && festivalNames.length > 0
        ? festivalNames.slice(0, 3).join(", ")
        : "upcoming events";
    insights.push(
      `🎉 ${meta.appliedFestivalDays} forecast day(s) adjusted for festival demand spikes (${festList}).`,
    );
  } else {
    insights.push("📅 No festival demand effects detected in this forecast window.");
  }

  const meaningful = externalInsights.filter(
    (s) =>
      !s.toLowerCase().includes("integrated into demand analysis") &&
      s.length > 30,
  );
  if (meaningful.length > 0) {
    meaningful.slice(0, 2).forEach((signal) => {
      const emoji = signal.toLowerCase().includes("rain")
        ? "🌧️"
        : signal.toLowerCase().includes("temperature") || signal.toLowerCase().includes("cold") || signal.toLowerCase().includes("heat")
        ? "🌡️"
        : signal.toLowerCase().includes("trend") || signal.toLowerCase().includes("market")
        ? "📈"
        : "🔍";
      insights.push(`${emoji} ${signal}`);
    });
  }

  return insights;
};

// ---------------------------------------------------------------------------
// SECTION 7: FESTIVAL NAME EXTRACTOR
// ---------------------------------------------------------------------------

export const extractFestivalNames = (
  forecastPoints: { festivalName?: string }[],
): string[] => {
  const seen = new Set<string>();
  forecastPoints.forEach((point) => {
    if (point.festivalName) seen.add(point.festivalName);
  });
  return Array.from(seen);
};

// ---------------------------------------------------------------------------
// SECTION 8: MAIN EXPORT - buildExplainableInsights
// ---------------------------------------------------------------------------

export const buildExplainableInsights = async (
  input: ExplainableInsightsInput,
): Promise<ExplainableInsightResult> => {
  const timestamp = new Date().toISOString();

  if (!input.forecastSignals?.summary || !input.groqApiKey?.trim()) {
    return {
      insights: buildFallbackInsights(input),
      source: "fallback",
      generatedAt: timestamp,
    };
  }

  const signalBlock = assembleSignalBlock(input);
  const prompt = buildGroqPrompt(signalBlock);

  const groqLines = await callGroqAPI(prompt, input.groqApiKey.trim());

  if (groqLines && groqLines.length >= 2) {
    return {
      insights: groqLines,
      source: "groq",
      generatedAt: timestamp,
    };
  }

  return {
    insights: buildFallbackInsights(input),
    source: "fallback",
    generatedAt: timestamp,
  };
};

